############################
## CHANGE THESE
############################

baseURL: "https://Krigs-hund.github.io/zu_im"
title: Zura Tattoo

############################
## MODULES
############################

module:
  imports:
    - path: github.com/chrede88/L1nkr

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
