############################
## Author
############################

author:
  name: Krigs-hund
  image: author.png
  greeting: "Связаться со мной 📱"
  icon: ":fire:"

############################
## Links
############################

links:
  - website: https://zutattoo.ru/
  - instagram: https://www.instagram.com/zura.tattoo
  - telegram: https://t.me/ZuraTattoo
  - whatsapp: https://wa.me/79996861312
 
############################
## Colunms of Links
############################

monochrome: true

# between 2 & 6 columns are supported (both incl)
columns: 2

###########################
## Icon text
###########################

# add the icon name to each icon
icontext: true

############################
## Tooltips
############################

# add tooltips on all icons
tooltip: false

###############################
## OpenGraph & Twitter Cards
###############################

title: zu_im
description: "Demo site build with L1nkr & Hugo"
images:
  - thumbnail.png

params:
  social_icons:
    - name: "vk"
      icon: "vk"